-- P2 Migration 001
-- Lead intake and processing foundation

CREATE TABLE IF NOT EXISTS public.lead_intake_events (
    intake_id TEXT PRIMARY KEY,

    external_lead_id TEXT NOT NULL,

    source TEXT NOT NULL CHECK (
        source IN (
            'demo_request',
            'website',
            'partner_referral',
            'outbound'
        )
    ),

    first_name TEXT,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    company_name TEXT NOT NULL,
    country TEXT,
    employee_count INTEGER CHECK (
        employee_count IS NULL OR employee_count >= 0
    ),

    raw_payload JSONB NOT NULL
        CHECK (jsonb_typeof(raw_payload) = 'object'),

    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (external_lead_id)
);

CREATE INDEX IF NOT EXISTS idx_lead_intake_external_id
    ON public.lead_intake_events (external_lead_id);

CREATE INDEX IF NOT EXISTS idx_lead_intake_email
    ON public.lead_intake_events (email);


CREATE TABLE IF NOT EXISTS public.lead_processing_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    intake_id TEXT NOT NULL REFERENCES public.lead_intake_events(intake_id)
        ON DELETE RESTRICT,

    attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),

    processing_status TEXT NOT NULL CHECK (
        processing_status IN (
            'received',
            'validated',
            'processing',
            'review_required',
            'failed',
            'retry_pending',
            'completed'
        )
    ),

    salesforce_lead_id TEXT,

    qualification_state TEXT,

    routing_target TEXT,

    sla_status TEXT,

    failure_type TEXT,
    failure_reason TEXT,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,

    UNIQUE (intake_id, attempt_number)
);

CREATE INDEX IF NOT EXISTS idx_lead_processing_intake
    ON public.lead_processing_attempts (intake_id);


ALTER TABLE public.lead_intake_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_processing_attempts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.lead_intake_events
FROM anon, authenticated;

REVOKE ALL ON public.lead_processing_attempts
FROM anon, authenticated;
